version: "3.7"

services: 
  database_proffy:
    image: postgres
    container_name: database_proffy
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=proffy
      - POSTGRES_DB=proffy
    volumes: 
      - pgdata:/data/postgres
  app:
    build: .
    container_name: proffy
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/project03
    links: 
      - database_proffy
    depends_on: 
      - database_proffy

volumes:
  pgdata:
    driver: local